language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

before_install:
- composer install
 
script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml
 
after_script:
- php vendor/bin/coveralls -v